"""Level decisions from the review of the course (tools/difficulty.py): where a piece sits in a different level
from the one it was first given, with the reason.  Level numbers: 0 Preparatory A, 1 Preparatory B, 2 Level 1 ... 7 Level 6.

Inside a level, make_lessons.py orders the pieces from the easiest to the hardest by the same estimate.
"""
MOVES = {
    # (new level, why)
    'chorale-68-4': (3, 'slow four-part block chords: easy to play, but chords in both hands'),
    'waltz-am': (3, 'only eight bars of a simple oom-pah-pah waltz'),
    'melody-68-1': (3, 'a plain tune over a simple accompaniment'),
    'first-noel': (3, 'a carol tune with a simple left hand'),
    'minuet-f-lmozart': (3, 'short and mostly hand-position playing'),
    'arirang': (3, 'a folk tune with a light accompaniment'),
    'aria-f-131': (3, 'two flowing lines in F major, no chords'),
    'aria-515': (3, 'two flowing lines in D minor, no chords'),
    'chorale-514': (3, 'two flowing lines in C major'),
    'greensleeves-easy': (3, 'a slow tune in 3/4 with a simple left hand'),
    'nachtmusik': (3, 'short opening theme with simple chords'),
    'telemann-andante': (3, 'slow 2/4 in G minor, two flats'),
    'sanctus': (3, 'a single chant line, but in four sharps'),
    'anh113': (4, 'a busy left hand: a minuet with a real bass melody'),
    'anh114': (4, 'the classic first minuet: both hands move independently'),
    'anh114-b': (4, 'same piece as the Anh. 114 minuet'),
    'anh114-c': (4, 'same piece as the Anh. 114 minuet'),
    'anh115': (4, 'minor key, two flats, both hands independent'),
    'anh115-b': (4, 'same piece as the Anh. 115 minuet'),
    'fur-elise': (4, 'the opening only, but fast sixteenth notes and hand changes'),
    'swan-lake': (4, 'a simple tune over chords in two sharps'),
    'little-piece-68-5': (4, 'a slow chordal piece'),
    'humming-68-3': (4, 'a slow chordal piece'),
    'morning-prayer': (4, 'a slow chordal piece'),
    'sonatina-c': (4, 'a short classical-style piece'),
    'fur-elise-beginner': (5, 'the whole piece, simplified'),
    'orphan-68-6': (5, 'slow, but with wide chords'),
    'clair-de-lune-easy': (5, 'slow 9/8 in an easy version'),
    'farmer-68-10': (5, 'a lively piece in a familiar position'),
    'chopin-nocturne-15': (5, 'slow, with a repeating left-hand pattern'),
    'polonaise-117b': (5, 'a short baroque dance'),
    'entertainer': (5, 'syncopation over a steady left hand, in an easy version'),
    'progres': (5, 'a fast study of simple five-finger patterns'),
    'petite-reunion': (5, 'a short lively piece in a fixed hand position'),
    'candeur': (5, 'a flowing study with simple harmony'),
    'old-french-song': (5, 'a simple tune with chords'),
    'blue-danube': (5, 'a waltz tune with an oom-pah-pah left hand'),
    'canon-in-c': (5, 'a repeating bass pattern under a growing melody'),
    'beethoven-5': (5, 'a short motif repeated in an easy arrangement'),
    'mozart-symphony-40': (5, 'a well-known theme in an easy arrangement'),
    'horseman-68-8': (5, 'a lively piece in a fixed hand position'),
    'consolation': (6, 'flowing arpeggios in the left hand'),
    'first-loss-68-16': (6, 'expressive, with changing harmony'),
    'foreign-lands': (6, 'a gentle melody in two voices'),
    'reapers-song-68-18': (6, 'a march-like piece in a fixed position'),
    'passacaglia': (6, 'a long piece, but an easy version'),
    'douce-plainte': (6, 'a lyrical study with chords'),
    'tendre-fleur': (6, 'a lyrical study with broken chords'),
    'bergeronnette': (6, 'a fast study with repeated notes'),
    'innocence': (6, 'a flowing study with broken chords'),
    'wooden-soldiers': (6, 'a march with chords in both hands'),
    'chopin-prelude-7': (6, 'only 16 bars, but chords and dotted rhythms'),
    'le-cygne': (6, 'a melody over rolling broken chords'),
    'chopin-nocturne-20-melody': (6, 'a single line, with fast runs and ornaments'),
    'chopin-nocturne-9-2-fuller': (6, 'a fuller arrangement of a famous nocturne'),
    'prelude-928': (6, 'broken chords in an even flow'),
    'prelude-924': (6, 'broken chords in an even flow'),
}
