"""Classical pieces taken from the Mutopia Project (https://www.mutopiaproject.org), converted from its MIDI files
(tools/sources/mutopia/) by midi_to_musicxml.py. Ornaments shorter than a 32nd note are left out and repeats
are played through once, as in the MIDI. Licences are those of the Mutopia editions: Public Domain, or
Creative Commons Attribution-ShareAlike for the Schumann pieces (our MusicXML versions keep that licence).
"""

MUTOPIA = 'https://www.mutopiaproject.org/cgibin/piece-info.cgi?id='
PD = 'Public Domain'
BYSA25, BYSA30 = 'CC BY-SA 2.5', 'CC BY-SA 3.0'
ANNA = 'Notebook for Anna Magdalena Bach'


def piece(id, src, level, title, composer, bpm, wait, license, learn, tips, pickup=0.0):
    return dict(id=id, src=src, level=level, kind='piece', title=title, composer=composer, hands='both', bpm=bpm, wait=wait,
                pickup=pickup, license=license, url=MUTOPIA + src.split('-')[0], learn=learn, tips=tips)


REPERTOIRE = [
    # ---------- Level 1 ----------
    piece('anh113', '74-0.mid', 2, 'Minuet in F (BWV Anh. 113)', ANNA, 100, 60, PD,
          'A short Baroque minuet from the notebook J. S. Bach kept for his wife, Anna Magdalena. Two independent lines: the left hand is a real bass melody, not just accompaniment.',
          ['Learn each hand alone first: both are melodies.', 'Feel the minuet in one gentle beat per bar.']),
    piece('anh120', '1612-0.mid', 2, 'Minuet in A minor (BWV Anh. 120)', ANNA, 90, 55, PD,
          'A minor-key minuet from the Anna Magdalena notebook. It begins with a pickup on beat 3.',
          ['Count "3 | 1 2 3" to start.', 'Keep the eighth notes even and light.'], pickup=1.0),
    # ---------- Level 2 ----------
    piece('anh114', '75-0.mid', 3, 'Minuet in G (BWV Anh. 114)', 'Christian Petzold (Notebook for Anna Magdalena Bach)', 110, 60, PD,
          'The famous Minuet in G, complete with its original left hand. Long a favourite first "real" classical piece.',
          ['The left hand moves in long notes under the dancing right hand.', 'Shape each four-bar phrase like a sentence.']),
    piece('anh115', '76-0.mid', 3, 'Minuet in G minor (BWV Anh. 115)', 'Christian Petzold (Notebook for Anna Magdalena Bach)', 110, 60, PD,
          'The companion piece to the Minuet in G: the same dance in a darker minor key.',
          ['Watch for F♯, the raised 7th of G minor.', 'Play the quarter notes slightly detached, the eighth notes smoothly.']),
    piece('aria-515', '78-0.mid', 3, 'Aria in D minor (BWV 515)', ANNA, 90, 55, PD,
          'A short, songlike aria from the Anna Magdalena notebook.',
          ['Sing the melody in your head as you play it.', 'Let the bass support without covering the tune.']),
    piece('melody-68-1', '647-0.mid', 3, 'Melody, Op. 68 No. 1', 'Robert Schumann (Album for the Young)', 70, 45, BYSA25,
          'The first piece of Schumann\'s Album for the Young: a singing melody over a flowing left hand.',
          ['Bring out the top line; keep the accompaniment soft.', 'Join the melody notes smoothly (legato).']),
    piece('march-68-2', '650-0.mid', 3, "Soldier's March, Op. 68 No. 2", 'Robert Schumann (Album for the Young)', 100, 60, BYSA25,
          'A crisp little march with chords in both hands. A steady beat is everything here.',
          ['Play the chords short and bright, exactly together.', 'March: never rush.']),
    # ---------- Level 3 ----------
    piece('anh116', '77-0.mid', 4, 'Minuet in G (BWV Anh. 116)', ANNA, 110, 60, PD,
          'Another minuet from the Anna Magdalena notebook, longer and more varied.',
          ['Practise the left hand alone until it is secure.', 'A few ornaments are left out; you can add them later.']),
    piece('anh118', '1014-0.mid', 4, 'Minuet in B♭ (BWV Anh. 118)', ANNA, 100, 60, PD,
          'A minuet in B♭ major (two flats).', ['B♭ and E♭ throughout.', 'Keep both hands equally clear.']),
    piece('anh121', '1613-0.mid', 4, 'Minuet in C minor (BWV Anh. 121)', ANNA, 100, 60, PD,
          'A serious, expressive minuet in C minor (three flats).', ['Watch for B♮, the raised 7th.', 'Let the bass line lead the harmony.']),
    piece('polonaise-117a', '1013-0.mid', 4, 'Polonaise in F (BWV Anh. 117a)', ANNA, 80, 50, PD,
          'A stately Polish dance in 3/4. Short ornaments are left out.', ['A polonaise is proud and steady, not fast.']),
    piece('humming-68-3', '651-0.mid', 4, 'Humming Song, Op. 68 No. 3', 'Robert Schumann (Album for the Young)', 60, 40, BYSA30,
          'A gentle song in which the melody passes between the hands.', ['Follow the tune as it moves from hand to hand.']),
    piece('chorale-68-4', '782-0.mid', 4, 'Chorale, Op. 68 No. 4', 'Robert Schumann (Album for the Young)', 80, 50, BYSA25,
          'A hymn in four parts: practise playing full chords smoothly and evenly.', ['Listen for the top voice in every chord.', 'Connect the chords without blurring them.']),
    piece('little-piece-68-5', '653-0.mid', 4, 'Little Piece, Op. 68 No. 5', 'Robert Schumann (Album for the Young)', 68, 45, BYSA25,
          'A short, flowing piece with a melody over steady accompaniment.', ['It starts with a long pickup: count it carefully.'], pickup=3.0),
    piece('morning-prayer', '2032-0.mid', 4, 'Morning Prayer, Op. 39 No. 1', 'Pyotr Ilyich Tchaikovsky (Album for the Young)', 60, 40, PD,
          'The opening piece of Tchaikovsky\'s Album for the Young: a quiet chorale in G major.', ['Play softly and very legato.', 'Hold every note its full length.']),
    # ---------- Level 4 ----------
    piece('orphan-68-6', '687-0.mid', 5, 'Poor Orphan Child, Op. 68 No. 6', 'Robert Schumann (Album for the Young)', 50, 35, BYSA25,
          'A sad little melody in A minor over chords.', ['Make the melody sing above the chords.'], pickup=0.5),
    piece('horseman-68-8', '655-0.mid', 5, 'The Wild Horseman, Op. 68 No. 8', 'Robert Schumann (Album for the Young)', 130, 70, BYSA25,
          'A galloping piece in 6/8 where the melody jumps from the right hand to the left.', ['Keep the gallop steady: "long-short".', 'Play the accompanying chords lightly.'], pickup=0.5),
    piece('farmer-68-10', '659-0.mid', 5, 'The Happy Farmer, Op. 68 No. 10', 'Robert Schumann (Album for the Young)', 90, 55, BYSA25,
          'The melody is in the left hand while the right hand plays chords: a classic for training the left hand to sing.', ['Bring out the left-hand tune.', 'Keep the right-hand chords short and soft.'], pickup=0.5),
    piece('old-french-song', '2080-0.mid', 5, 'Old French Song, Op. 39 No. 16', 'Pyotr Ilyich Tchaikovsky (Album for the Young)', 70, 45, PD,
          'A wistful melody in G minor over a smooth accompaniment.', ['Shape the long phrases.', 'Use the tied notes to let the melody breathe.'], pickup=0.5),
    piece('handel-sonatina', '98-0.mid', 5, 'Sonatina in B♭ (HWV 585)', 'George Frideric Handel', 100, 60, PD,
          'A lively Baroque sonatina with busy lines in both hands.', ['Practise slowly and hands separately first.', 'Aim for crisp, even sixteenths.']),
    piece('candeur', '202-0.mid', 5, 'Candour (La Candeur), Op. 100 No. 1', 'Friedrich Burgmüller (25 Easy Studies)', 120, 70, PD,
          'The first of Burgmüller\'s 25 Easy Studies: a smooth melody over gentle broken chords.', ['Keep the melody legato and singing.']),
    piece('arabesque', '203-0.mid', 5, 'Arabesque, Op. 100 No. 2', 'Friedrich Burgmüller (25 Easy Studies)', 120, 70, PD,
          'A favourite study with quick five-note runs in A minor.', ['Practise the runs slowly; keep the fingers close to the keys.']),
    piece('pastorale', '218-0.mid', 5, 'Pastorale, Op. 100 No. 3', 'Friedrich Burgmüller (25 Easy Studies)', 90, 55, PD,
          'A peaceful country scene in 6/8. Short ornaments are left out.', ['Rock gently in two beats per bar.']),
    piece('clementi-36-1-i', '804-2.mid', 5, 'Sonatina in C, Op. 36 No. 1: I. Spiritoso', 'Muzio Clementi', 120, 70, PD,
          'The first movement of perhaps the most famous sonatina of all: scales, broken chords and a bright, clear style.', ['Play the scales evenly and crisply.', 'Feel the music in two big beats per bar.']),
    piece('clementi-36-1-ii', '804-0.mid', 5, 'Sonatina in C, Op. 36 No. 1: II. Andante', 'Muzio Clementi', 70, 45, PD,
          'The slow middle movement, in F major: a gentle, singing melody. Short ornaments are left out.', ['Make the melody sing; keep the left hand quiet.']),
    piece('clementi-36-1-iii', '804-1.mid', 5, 'Sonatina in C, Op. 36 No. 1: III. Vivace', 'Muzio Clementi', 100, 60, PD,
          'The lively finale in 3/8.', ['Feel one beat per bar once it is secure.', 'Keep the repeated notes light.']),
    # ---------- Level 5 ----------
    piece('petite-reunion', '219-0.mid', 6, 'The Little Party (La Petite Réunion), Op. 100 No. 4', 'Friedrich Burgmüller (25 Easy Studies)', 110, 65, PD,
          'Lively repeated chords and quick changes of hand position.', ['Keep the repeated chords light, from the wrist.']),
    piece('innocence', '214-0.mid', 6, 'Innocence, Op. 100 No. 5', 'Friedrich Burgmüller (25 Easy Studies)', 90, 55, PD,
          'A graceful 3/4 study with flowing runs in F major.', ['Shape every run with a small swell and fade.']),
    piece('progres', '215-0.mid', 6, 'Progress (Progrès), Op. 100 No. 6', 'Friedrich Burgmüller (25 Easy Studies)', 100, 60, PD,
          'Scales and broken chords shared between the hands: a study in evenness.', ['Practise the hand changes slowly so the runs sound like one line.']),
    piece('courant-limpide', '216-0.mid', 6, 'The Limpid Stream (Le Courant Limpide), Op. 100 No. 7', 'Friedrich Burgmüller (25 Easy Studies)', 120, 70, PD,
          'Rippling sixteenths in the right hand over a calm left-hand melody.', ['Keep the right hand soft and even; let the left hand sing.']),
    piece('gracieuse', '217-0.mid', 6, 'The Graceful One (La Gracieuse), Op. 100 No. 8', 'Friedrich Burgmüller (25 Easy Studies)', 80, 50, PD,
          'An elegant piece in F major with turns and delicate ornaments (the shortest are left out).', ['Play lightly and gracefully, never heavy.']),
    piece('tendre-fleur', '221-0.mid', 6, 'Tender Flower (Tendre Fleur), Op. 100 No. 10', 'Friedrich Burgmüller (25 Easy Studies)', 110, 65, PD,
          'Chords and short slurs in D major: practise a gentle, controlled touch.', ['Lift at the end of each two-note slur.']),
    piece('bergeronnette', '222-0.mid', 6, 'The Wagtail (La Bergeronnette), Op. 100 No. 11', 'Friedrich Burgmüller (25 Easy Studies)', 120, 70, PD,
          'Quick, light figures that flick between the hands like a little bird.', ['Keep the fingers close to the keys for speed.']),
    piece('petite-etude-68-14', '786-0.mid', 6, 'Little Study, Op. 68 No. 14', 'Robert Schumann (Album for the Young)', 120, 70, BYSA25,
          'Broken chords shared between the hands in a smooth 6/8 flow.', ['Make the hand changes invisible: one continuous line.']),
    piece('wooden-soldiers', '1806-0.mid', 6, 'March of the Wooden Soldiers, Op. 39 No. 5', 'Pyotr Ilyich Tchaikovsky (Album for the Young)', 110, 65, PD,
          'A crisp toy-soldier march with dotted rhythms in D major.', ['Keep the dotted rhythms sharp and the tempo steady.']),
    piece('polonaise-117b', '1015-0.mid', 6, 'Polonaise in F (BWV Anh. 117b)', ANNA, 60, 40, PD,
          'A more ornamented version of the F major polonaise (the shortest ornaments are left out).', ['Stately, not fast.']),
    # ---------- Level 6 ----------
    piece('la-chasse', '220-0.mid', 7, 'The Hunt (La Chasse), Op. 100 No. 9', 'Friedrich Burgmüller (25 Easy Studies)', 140, 80, PD,
          'Hunting horns and galloping horses in 6/8: crossing hands and crisp staccato.', ['Keep the gallop rhythm steady.'], pickup=0.5),
    piece('adieu', '223-0.mid', 7, "Farewell (L'Adieu), Op. 100 No. 12", 'Friedrich Burgmüller (25 Easy Studies)', 120, 70, PD,
          'An agitated piece in A minor with a melody over restless sixteenths.', ['Bring out the melody notes above the accompaniment.'], pickup=0.5),
    piece('consolation', '224-0.mid', 7, 'Consolation, Op. 100 No. 13', 'Friedrich Burgmüller (25 Easy Studies)', 100, 60, PD,
          'A warm, singing melody over broken-chord accompaniment.', ['Let the melody sing; keep the accompaniment soft and even.']),
    piece('ballade-burgmuller', '227-0.mid', 7, 'Ballade, Op. 100 No. 15', 'Friedrich Burgmüller (25 Easy Studies)', 90, 55, PD,
          'A dramatic story in C minor with a lyrical middle section in C major.', ['Contrast the stormy staccato with the singing middle part.']),
    piece('douce-plainte', '228-0.mid', 7, 'Gentle Lament (Douce Plainte), Op. 100 No. 16', 'Friedrich Burgmüller (25 Easy Studies)', 90, 55, PD,
          'A sorrowful melody in G minor with expressive slurs.', ['Lean gently on the first note of each slur.']),
    piece('babillarde', '229-0.mid', 7, 'The Chatterbox (La Babillarde), Op. 100 No. 17', 'Friedrich Burgmüller (25 Easy Studies)', 90, 55, PD,
          'Fast chattering figures in 3/8: lightness and even fingers.', ['Practise slowly in short groups, then join them.']),
    piece('inquietude', '230-0.mid', 7, 'Restlessness (Inquiétude), Op. 100 No. 18', 'Friedrich Burgmüller (25 Easy Studies)', 100, 60, PD,
          'Nervous, quick figures passed between the hands in E minor.', ['Keep the hand changes rhythmically exact.']),
    piece('may-68-13', '662-0.mid', 7, 'May, Dear May, Op. 68 No. 13', 'Robert Schumann (Album for the Young)', 50, 35, BYSA25,
          'A springtime piece in E major (four sharps) with a gentle, singing line.', ['Watch the key signature: F♯, C♯, G♯ and D♯.'], pickup=0.5),
    piece('first-loss-68-16', '676-0.mid', 7, 'First Loss, Op. 68 No. 16', 'Robert Schumann (Album for the Young)', 70, 45, BYSA25,
          'A short, heartfelt piece in E minor: one of the best-loved of the Album.', ['Make the melody sing with expression.'], pickup=0.5),
    piece('reapers-song-68-18', '663-0.mid', 7, "Reaper's Song, Op. 68 No. 18", 'Robert Schumann (Album for the Young)', 100, 60, BYSA25,
          'A cheerful harvest song in 6/8 with melody and accompaniment in the same hand.', ['Hold the melody notes while the other fingers play.']),
    piece('foreign-lands', '354-0.mid', 7, 'Of Foreign Lands and Peoples, Op. 15 No. 1', 'Robert Schumann (Scenes from Childhood)', 60, 40, PD,
          "The first of Schumann's Scenes from Childhood: a melody floating above gentle broken chords.", ['Voice the melody on top; keep the inner notes very soft.']),
    piece('prelude-928', '493-0.mid', 7, 'Little Prelude in F (BWV 928)', 'Johann Sebastian Bach', 60, 40, PD,
          'A Little Prelude with busy sixteenths in both hands.', ['Practise hands separately until each line is smooth.']),
    piece('prelude-924', '978-0.mid', 7, 'Little Prelude in C (BWV 924)', 'Johann Sebastian Bach', 50, 35, BYSA30,
          'Broken chords in the right hand over a slow bass: like a small cousin of the Prelude in C.', ['Let the harmony changes shape the music.']),
    piece('prelude-999', '60-0.mid', 7, 'Prelude in D minor (BWV 999)', 'Johann Sebastian Bach', 70, 45, PD,
          'Originally for lute (in C minor; this edition is in D minor): steady broken chords in 3/4 over a moving bass.', ['Keep the broken chords perfectly even.']),
]


# ---------- Levels 5-10 from the RCM Piano Syllabus 2022 lists (Mutopia Project) ----------
BYSA40, BY30 = 'CC BY-SA 4.0', 'CC BY 3.0'
BACH, CHOPIN, SCHUMANN = 'Johann Sebastian Bach', 'Frédéric Chopin', 'Robert Schumann (Album for the Young)'
INV_TIPS = ['Practise each hand alone first: both hands play the same theme in turn.', 'Listen for the theme as it moves from hand to hand, and keep the other hand quiet.']
SIN_TIPS = ['Three voices: learn each one alone, then two at a time.', 'Let the entry of each voice be heard.']
PRE_TIPS = ['Learn it in short sections, each hand alone first.', 'Shape the long phrases with the dynamics.']

REPERTOIRE += [
    # ---------- Level 5 ----------
    piece('schumann-68-7', '691-0.mid', 6, 'Hunting Song, Op. 68 No. 7', SCHUMANN, 120, 70, BYSA30,
          'A galloping 6/8 hunting piece with horn calls in the right hand and a lively left hand.', ['Count in two big beats: "ONE-two-three TWO-two-three".', 'Keep the horn calls bright and the left hand lighter.'], pickup=0.5),
    piece('schumann-68-9', '675-0.mid', 6, 'Little Folk Song, Op. 68 No. 9', SCHUMANN, 88, 60, BYSA25,
          'A simple folk-like tune in a minor-flavoured key, with a steady accompaniment.', ['Sing the tune in your head as you play.', 'Keep the accompaniment quiet.']),
    piece('schumann-68-11', '783-0.mid', 6, 'Sicilienne, Op. 68 No. 11', SCHUMANN, 96, 60, BYSA25,
          'A gently rocking Sicilian dance in 6/8, beginning with a pickup note.', ['Feel the lilt: long-short-long.', 'Start with the pickup note on the last eighth of the bar.'], pickup=0.5),
    # ---------- Level 6 ----------
    piece('kuhlau-20-1-i', '232-0.mid', 7, 'Sonatina in C, Op. 20 No. 1: I. Allegro', 'Friedrich Kuhlau', 120, 70, PD,
          'The first movement of a classic sonatina, with rapid triplet figures in the right hand over a steady bass.', ['Practise the triplet runs slowly with Wait for me.', 'Keep the left hand steady and light.']),
    piece('kuhlau-20-1-ii', '233-0.mid', 7, 'Sonatina in C, Op. 20 No. 1: II. Andante', 'Friedrich Kuhlau', 76, 50, PD,
          'A lyrical slow movement in 6/8 (F major) after the lively Allegro.', ['Sing the melody; keep the accompaniment even.'], pickup=0.5),
    piece('kuhlau-20-1-iii', '234-0.mid', 8, 'Sonatina in C, Op. 20 No. 1: III. Rondo', 'Friedrich Kuhlau', 132, 80, PD,
          'A bright rondo finale: a returning theme between contrasting episodes.', ['Learn the theme first; it returns several times.', 'Practise the episodes in sections.'], pickup=0.5),
    # ---------- Level 7 ----------
    piece('invention-1', '40-0.mid', 8, 'Two-part Invention No. 1 in C major, BWV 772', BACH, 66, 45, BYSA30,
          'The first of the two-part inventions: a short theme passed between the hands, and answered upside down.', INV_TIPS),
    piece('invention-4', '67-0.mid', 8, 'Two-part Invention No. 4 in D minor, BWV 775', BACH, 80, 50, PD,
          'A quick invention in 3/8 in D minor: a rushing theme in sixteenth notes.', INV_TIPS),
    piece('invention-8', '61-0.mid', 8, 'Two-part Invention No. 8 in F major, BWV 779', BACH, 72, 50, PD,
          'A cheerful invention in F major in 3/4: a leaping theme answered in the left hand.', INV_TIPS),
    piece('grieg-album-leaf', '2194-0.mid', 8, 'Album Leaf, Op. 12 No. 7', 'Edvard Grieg', 76, 50, BYSA40,
          'A tender lyric piece in E minor: a singing melody over soft chords, starting with a pickup.', ['Let the melody sing and keep the chords soft.', 'Start with the pickup on the last eighth of the bar.'], pickup=0.5),
    # ---------- Level 8 ----------
    piece('invention-2', '58-0.mid', 9, 'Two-part Invention No. 2 in C minor, BWV 773', BACH, 56, 40, PD,
          'A flowing invention in C minor with a smooth sixteenth-note theme.', INV_TIPS),
    piece('invention-3', '70-0.mid', 9, 'Two-part Invention No. 3 in D major, BWV 774', BACH, 84, 55, PD,
          'A light, dancing invention in 3/8, starting with a pickup.', INV_TIPS, pickup=0.5),
    piece('invention-5', '55-0.mid', 9, 'Two-part Invention No. 5 in E-flat major, BWV 776', BACH, 64, 45, PD,
          'A stately invention in E♭ major with a lively sixteenth-note figure.', INV_TIPS),
    piece('invention-6', '159-0.mid', 9, 'Two-part Invention No. 6 in E major, BWV 777', BACH, 84, 55, BYSA30,
          'A bright invention in E major (four sharps) in 3/8.', INV_TIPS),
    piece('invention-7', '73-0.mid', 9, 'Two-part Invention No. 7 in E minor, BWV 778', BACH, 60, 45, PD,
          'A serious invention in E minor with a descending, chromatic theme.', INV_TIPS),
    piece('invention-9', '171-0.mid', 9, 'Two-part Invention No. 9 in F minor, BWV 780', BACH, 56, 40, BYSA30,
          'The "sighing" invention in F minor (four flats), full of expressive falling figures.', INV_TIPS),
    piece('invention-10', '62-0.mid', 9, 'Two-part Invention No. 10 in G major, BWV 781', BACH, 66, 45, PD,
          'A bubbling invention in 9/8 (three groups of three eighth notes per bar).', INV_TIPS),
    piece('invention-11', '71-0.mid', 9, 'Two-part Invention No. 11 in G minor, BWV 782', BACH, 66, 45, PD,
          'A lyrical invention in G minor with a long, graceful theme.', INV_TIPS),
    piece('duetto-f', '360-0.mid', 9, 'Duetto in F major, BWV 803', BACH, 96, 60, PD,
          'One of the four duets from the third part of the Clavier-Übung: two lively lines in a free fugal style.', INV_TIPS),
    piece('chopin-prelude-6', '469-0.mid', 9, 'Prelude in B minor, Op. 28 No. 6', CHOPIN, 66, 45, PD,
          'A sombre prelude: a mournful melody in the left hand over repeated chords in the right.', PRE_TIPS),
    piece('chopin-prelude-9', '2168-0.mid', 9, 'Prelude in E major, Op. 28 No. 9', CHOPIN, 54, 40, BYSA40,
          'A slow, solemn prelude of only twelve bars in four sharps, with rich chords.', PRE_TIPS),
    piece('gnossienne-3', '2131-0.mid', 9, 'Gnossienne No. 3', 'Erik Satie', 60, 45, BYSA40,
          'A slow, mysterious dance with a swaying left hand and a melody in the right.', ['Play very quietly and slowly.', 'Keep the left-hand pattern perfectly even.']),
    # ---------- Level 9 ----------
    piece('sinfonia-1', '142-0.mid', 10, 'Sinfonia No. 1 in C major, BWV 787', BACH, 66, 45, PD, 'The first three-part invention: three voices in imitation.', SIN_TIPS),
    piece('sinfonia-2', '140-0.mid', 10, 'Sinfonia No. 2 in C minor, BWV 788', BACH, 54, 40, PD, 'A flowing three-part invention in C minor in 12/8.', SIN_TIPS),
    piece('sinfonia-3', '143-0.mid', 10, 'Sinfonia No. 3 in D major, BWV 789', BACH, 72, 50, PD, 'A bright three-part invention in D major.', SIN_TIPS),
    piece('sinfonia-4', '172-0.mid', 10, 'Sinfonia No. 4 in D minor, BWV 790', BACH, 66, 45, PD, 'A restless three-part invention in D minor.', SIN_TIPS),
    piece('sinfonia-5', '204-0.mid', 10, 'Sinfonia No. 5 in E-flat major, BWV 791', BACH, 66, 45, PD, 'A graceful three-part invention in 3/4 in E♭ major.', SIN_TIPS),
    piece('sinfonia-6', '173-0.mid', 10, 'Sinfonia No. 6 in E major, BWV 792', BACH, 58, 40, PD, 'A flowing three-part invention in 9/8 in E major.', SIN_TIPS),
    piece('chopin-prelude-13', '2174-0.mid', 10, 'Prelude in F-sharp major, Op. 28 No. 13', CHOPIN, 54, 40, BYSA40,
          'A calm, singing prelude in six sharps, with a long melody over a gentle accompaniment.', PRE_TIPS),
    piece('chopin-prelude-15', '471-0.mid', 10, 'Prelude in D-flat major, Op. 28 No. 15 ("Raindrop")', CHOPIN, 60, 45, PD,
          'The "Raindrop" prelude: a repeated note keeps sounding through the calm opening and the dark middle section.', PRE_TIPS),
    piece('chopin-mazurka-6-1', '1687-0.mid', 10, 'Mazurka in F-sharp minor, Op. 6 No. 1', CHOPIN, 120, 70, BY30,
          'A Polish dance in 3/4 with accents on the second and third beats.', ['Feel the accent on beats 2 and 3.', 'Keep the left hand light.']),
    piece('chopin-nocturne-9-2-full', '1590-0.mid', 10, 'Nocturne in E-flat, Op. 9 No. 2', CHOPIN, 56, 40, BYSA30,
          'The complete famous nocturne in 12/8, with its decorated returns of the melody. Begins with a pickup.', PRE_TIPS, pickup=0.5),
    # ---------- Level 10 ----------
    piece('wtc-fugue-1', '4-0.mid', 11, 'Fugue in C major, BWV 846 (Well-Tempered Clavier I)', BACH, 66, 45, PD,
          'The famous four-voice fugue in C: the subject enters in each voice in turn.', SIN_TIPS + ['Follow the subject every time it enters.']),
    piece('chopin-prelude-17', '2190-0.mid', 11, 'Prelude in A-flat major, Op. 28 No. 17', CHOPIN, 60, 45, BYSA40,
          'A long, rich prelude in four flats, with a singing melody over repeated chords.', PRE_TIPS),
    piece('chopin-nocturne-9-1', '582-0.mid', 11, 'Nocturne in B-flat minor, Op. 9 No. 1', CHOPIN, 52, 36, BYSA25,
          'A dark, expressive nocturne in five flats, beginning with a long pickup.', PRE_TIPS, pickup=3.0),
    piece('clair-de-lune', '1778-0.mid', 11, 'Clair de lune (Suite bergamasque)', 'Claude Debussy', 60, 40, PD,
          'Debussy\'s famous moonlit piece in D♭ major in 9/8: floating arpeggios and a soft melody.', ['Play very softly and let the pedal blur the harmonies gently.', 'Keep the arpeggios smooth and even.']),
    piece('troldhaugen', '781-0.mid', 11, 'Wedding Day at Troldhaugen, Op. 65 No. 6', 'Edvard Grieg', 108, 70, PD,
          'Grieg\'s lively wedding march: bold chords, rapid figures and a joyful melody.', ['Learn it in sections of eight bars.', 'Keep the chords crisp and the tune bright.']),
]
